#!/usr/bin/env bash
# extract-ims-blobs.sh — stage the QTI IMS userspace out of the stock ether zip.
#
#   ./extract-ims-blobs.sh <stock.zip> <aosp-root>
#
# WHY this is not just added to proprietary-files.txt: vendor/nextbit/ether comes from TheMuppets
# via the manifest, and TheMuppets deliberately omits the IMS set (LineageOS disabled the pre-P IMS
# stack — bullhead 5cef16f, which removed exactly one line from its blobs list). Patching a synced
# vendor repo to carry blobs we cannot commit is worse than staging them, so this follows the same
# shape as the oem option: everything lands under vendor/extra, which apply-overlay clears per build.
#
# Reads proprietary-files-ims.txt beside this script. Lines are `src[:dest]`, src relative to
# system/ in the zip; dest defaults to src. See VOLTE.md.
#
# The blobs are proprietary: they are staged into the tree at build time and never committed.
set -u
ZIP="${1:?usage: extract-ims-blobs.sh <stock.zip> <aosp-root>}"
AOSP="${2:?usage: extract-ims-blobs.sh <stock.zip> <aosp-root>}"
LIST="$(cd "$(dirname "$0")" && pwd)/proprietary-files-ims.txt"
[ -f "$ZIP" ]  || { echo "!! no such zip: $ZIP" >&2; exit 1; }
[ -d "$AOSP" ] || { echo "!! no such tree: $AOSP" >&2; exit 1; }
[ -f "$LIST" ] || { echo "!! missing $LIST" >&2; exit 1; }

# NOT vendor/extra: apply-overlay does "rm -rf vendor/extra" at the start of every build, so anything
# staged there before bootstrap runs is deleted at step [4/5] and the image silently ships without
# it. The oem option survives only because bootstrap runs its extractor at [4b], AFTER that clear.
# This tool is run by hand before a build, so it needs a directory nobody wipes -- and it clears its
# own, which is what the vendor/extra clear was protecting against.
DEST="$AOSP/vendor/ims-blobs"
REL="vendor/ims-blobs"
TMP="${TMPDIR:-$AOSP/out/tmp}/ims-extract.$$"
rm -rf "$DEST" "$TMP"; mkdir -p "$DEST" "$TMP" || exit 1
trap 'rm -rf "$TMP"' EXIT

echo ">> staging IMS blobs from $(basename "$ZIP")"
n=0; miss=0
: > "$TMP/copy.list"
while IFS= read -r line; do
  case "$line" in ''|\#*) continue ;; esac
  src="${line%%:*}"; dst="${line#*:}"; [ "$dst" = "$line" ] && dst="$src"
  dst="${dst%%|*}"                       # a |sha1 pin is not part of the path
  if ! unzip -q -o -j "$ZIP" "system/$src" -d "$TMP/one" 2>/dev/null; then
    echo "   !! not in zip: $src" >&2; miss=$((miss+1)); continue
  fi
  mkdir -p "$DEST/$(dirname "$dst")"
  mv "$TMP/one/$(basename "$src")" "$DEST/$dst" || { miss=$((miss+1)); continue; }
  # The destination decides the partition, not the source: only paths that are already under
  # vendor/ belong on the vendor partition. framework/, priv-app/ and etc/ are system-side, and
  # forcing them to vendor silently produces an image where the IMS jars are in a place the boot
  # classpath never looks.
  case "$dst" in
    vendor/*) echo "    $REL/$dst:\$(TARGET_COPY_OUT_VENDOR)/${dst#vendor/} \\" >> "$TMP/copy.list" ;;
    *)        echo "    $REL/$dst:\$(TARGET_COPY_OUT_SYSTEM)/$dst \\"           >> "$TMP/copy.list" ;;
  esac
  n=$((n+1))
done < "$LIST"

# PRODUCT_COPY_FILES for everything; the apks are copied verbatim too, because they are odexed
# against the 7.1 boot image and must not be re-signed or re-compiled by the build.
{
  echo "# Generated by extract-ims-blobs.sh — do not edit."
  echo "# QTI IMS userspace from the stock ether image. See VOLTE.md."
  echo
  echo "PRODUCT_COPY_FILES += \\"
  sed 's|\$(TARGET_COPY_OUT_VENDOR)/vendor/|$(TARGET_COPY_OUT_VENDOR)/|' "$TMP/copy.list" | sed '$ s/ \\$//'
} > "$DEST/ims-blobs.mk"

echo ">> staged $n file(s) into $REL"
[ "$miss" -eq 0 ] || echo "!! $miss file(s) missing from the zip — the list and the image disagree" >&2
echo ">> wrote $REL/ims-blobs.mk"
[ "$miss" -eq 0 ]
